// LLVMCodeGen.swift
// RockitKit — Rockit Language Compiler
// Copyright © 2026 Dark Matter Tech. All rights reserved.

import Foundation

// MARK: - LLVM Code Generator

/// Generates LLVM IR text (.ll) from an optimized MIR module.
/// The emitted IR uses alloca-based register mapping; LLVM's mem2reg pass
/// (triggered by clang -O1) promotes allocas to SSA form.
public final class LLVMCodeGen {

    /// Counter for unique SSA names within a function.
    private var ssaCounter: Int = 0
    /// Map from MIR register names to their alloca LLVM names.
    private var registerMap: [String: String] = [:]
    /// Map from MIR register names to their LLVM type string.
    private var registerTypes: [String: String] = [:]
    /// String literal pool: value → global name.
    private var stringPool: [String: String] = [:]
    /// Counter for string literal globals.
    private var stringCounter: Int = 0
    /// Collected function declarations (externals).
    private var externalDecls: Set<String> = []
    /// Current function's parameter names for `param.X` resolution.
    private var currentParams: [(String, MIRType)] = []
    /// Map from param name → LLVM argument name.
    private var paramMap: [String: String] = [:]
    /// The module's type declarations for field index lookup.
    private var typeDecls: [String: MIRTypeDecl] = [:]
    /// Map from function name → return type for user-defined functions.
    private var functionSignatures: [String: MIRType] = [:]
    /// Current class name when emitting a method (for `global.X` → field resolution).
    private var currentClassName: String? = nil
    /// String pool for type name constants (separate from string literals).
    private var typeNamePool: [String: String] = [:]
    /// Counter for type name constants.
    private var typeNameCounter: Int = 0
    /// Map from catch block label → exception dest temp name.
    private var catchBlocks: [String: String] = [:]

    public init() {}

    // MARK: - Public API

    /// Emit LLVM IR text for the entire MIR module.
    public func emit(module: MIRModule) -> String {
        // Reset state
        ssaCounter = 0
        registerMap = [:]
        registerTypes = [:]
        stringPool = [:]
        stringCounter = 0
        externalDecls = []
        typeDecls = [:]
        functionSignatures = [:]
        currentClassName = nil
        typeNamePool = [:]
        typeNameCounter = 0

        // Index type declarations
        for t in module.types {
            typeDecls[t.name] = t
        }

        // Index function signatures for call-site return type resolution
        for f in module.functions {
            functionSignatures[f.name] = f.returnType
        }

        // Pre-pass: correct method return types by analyzing function bodies
        // MIR lowering may emit .unit for methods that actually return values
        for f in module.functions where f.returnType == .unit {
            let inferred = inferActualReturnType(f)
            if inferred != "void" {
                // Store a synthetic MIR type that maps to the inferred LLVM type
                switch inferred {
                case "i64": functionSignatures[f.name] = .int
                case "double": functionSignatures[f.name] = .float64
                case "i1": functionSignatures[f.name] = .bool
                case "ptr": functionSignatures[f.name] = .string  // ptr could be string or object
                default: break
                }
            }
        }

        var lines: [String] = []

        // Module header
        lines.append("; Rockit LLVM IR — generated by command (Stage 0)")
        lines.append("target triple = \"\(targetTriple())\"")
        lines.append("")

        // Collect string literals and type names from all functions
        collectStrings(module: module)
        collectTypeNames(module: module)

        // Emit string literal globals
        for (value, name) in stringPool.sorted(by: { $0.value < $1.value }) {
            let escaped = llvmEscapeString(value)
            let len = value.utf8.count + 1  // +1 for null terminator
            lines.append("\(name) = private unnamed_addr constant [\(len) x i8] c\"\(escaped)\\00\"")
        }
        // Emit type name globals (for rockit_object_alloc)
        for (value, name) in typeNamePool.sorted(by: { $0.value < $1.value }) {
            let escaped = llvmEscapeString(value)
            let len = value.utf8.count + 1
            lines.append("\(name) = private unnamed_addr constant [\(len) x i8] c\"\(escaped)\\00\"")
        }
        if !stringPool.isEmpty || !typeNamePool.isEmpty {
            lines.append("")
        }

        // Emit external declarations
        collectExternals(module: module)
        for decl in externalDecls.sorted() {
            lines.append(decl)
        }
        if !externalDecls.isEmpty {
            lines.append("")
        }

        // Emit attributes (for setjmp returns_twice)
        lines.append("attributes #0 = { returns_twice }")
        lines.append("")

        // Emit functions
        for function in module.functions {
            lines.append(emitFunction(function))
            lines.append("")
        }

        return lines.joined(separator: "\n")
    }

    // MARK: - Target Triple

    private func targetTriple() -> String {
        // Detect host triple at runtime to avoid version mismatch warnings
        #if arch(arm64) && os(macOS)
        let arch = "arm64-apple-macosx"
        #elseif arch(x86_64) && os(macOS)
        let arch = "x86_64-apple-macosx"
        #elseif arch(x86_64) && os(Linux)
        return "x86_64-unknown-linux-gnu"
        #elseif arch(arm64) && os(Linux)
        return "aarch64-unknown-linux-gnu"
        #else
        return "x86_64-unknown-linux-gnu"
        #endif

        #if os(macOS)
        let version = ProcessInfo.processInfo.operatingSystemVersion
        return "\(arch)\(version.majorVersion).0.0"
        #endif
    }

    // MARK: - String Collection

    private func collectStrings(module: MIRModule) {
        for function in module.functions {
            for block in function.blocks {
                for inst in block.instructions {
                    if case .constString(_, let value) = inst {
                        internString(value)
                    }
                }
            }
        }
    }

    private func collectTypeNames(module: MIRModule) {
        for function in module.functions {
            for block in function.blocks {
                for inst in block.instructions {
                    if case .newObject(_, let typeName, _) = inst {
                        internTypeName(typeName)
                    }
                }
            }
        }
    }

    @discardableResult
    private func internTypeName(_ value: String) -> String {
        if let existing = typeNamePool[value] {
            return existing
        }
        let name = "@.typename.\(typeNameCounter)"
        typeNameCounter += 1
        typeNamePool[value] = name
        return name
    }

    @discardableResult
    private func internString(_ value: String) -> String {
        if let existing = stringPool[value] {
            return existing
        }
        let name = "@.str.\(stringCounter)"
        stringCounter += 1
        stringPool[value] = name
        return name
    }

    // MARK: - External Declarations

    private func collectExternals(module: MIRModule) {
        // Always declare runtime functions we might use
        externalDecls.insert("declare void @rockit_println_int(i64)")
        externalDecls.insert("declare void @rockit_println_float(double)")
        externalDecls.insert("declare void @rockit_println_bool(i1)")
        externalDecls.insert("declare void @rockit_println_string(ptr)")
        externalDecls.insert("declare void @rockit_println_null()")
        externalDecls.insert("declare void @rockit_print_int(i64)")
        externalDecls.insert("declare void @rockit_print_float(double)")
        externalDecls.insert("declare void @rockit_print_bool(i1)")
        externalDecls.insert("declare void @rockit_print_string(ptr)")
        externalDecls.insert("declare ptr @rockit_string_new(ptr)")
        externalDecls.insert("declare ptr @rockit_string_concat(ptr, ptr)")
        externalDecls.insert("declare void @rockit_string_retain(ptr)")
        externalDecls.insert("declare void @rockit_string_release(ptr)")
        externalDecls.insert("declare i64 @rockit_string_length(ptr)")
        externalDecls.insert("declare ptr @rockit_int_to_string(i64)")
        externalDecls.insert("declare ptr @rockit_float_to_string(double)")
        externalDecls.insert("declare ptr @rockit_bool_to_string(i1)")
        externalDecls.insert("declare void @rockit_panic(ptr)")
        // Object runtime
        externalDecls.insert("declare ptr @rockit_object_alloc(ptr, i32)")
        externalDecls.insert("declare i64 @rockit_object_get_field(ptr, i32)")
        externalDecls.insert("declare void @rockit_object_set_field(ptr, i32, i64)")
        externalDecls.insert("declare void @rockit_retain(ptr)")
        externalDecls.insert("declare void @rockit_release(ptr)")
        // List runtime
        externalDecls.insert("declare ptr @rockit_list_create()")
        externalDecls.insert("declare void @rockit_list_append(ptr, i64)")
        externalDecls.insert("declare i64 @rockit_list_get(ptr, i64)")
        externalDecls.insert("declare void @rockit_list_set(ptr, i64, i64)")
        externalDecls.insert("declare i64 @rockit_list_size(ptr)")
        externalDecls.insert("declare i1 @rockit_list_is_empty(ptr)")
        // Map runtime
        externalDecls.insert("declare ptr @rockit_map_create()")
        externalDecls.insert("declare void @rockit_map_put(ptr, i64, i64)")
        externalDecls.insert("declare i64 @rockit_map_get(ptr, i64)")
        externalDecls.insert("declare i1 @rockit_map_contains_key(ptr, i64)")
        externalDecls.insert("declare i64 @rockit_map_size(ptr)")
        externalDecls.insert("declare i1 @rockit_map_is_empty(ptr)")
        // Exception handling
        externalDecls.insert("declare ptr @rockit_exc_push()")
        externalDecls.insert("declare void @rockit_exc_pop()")
        externalDecls.insert("declare void @rockit_exc_throw(i64)")
        externalDecls.insert("declare i64 @rockit_exc_get()")
        externalDecls.insert("declare i32 @_setjmp(ptr) #0")
    }

    // MARK: - Function Emission

    private func emitFunction(_ function: MIRFunction) -> String {
        // Reset per-function state
        ssaCounter = 0
        registerMap = [:]
        registerTypes = [:]
        currentParams = function.parameters
        paramMap = [:]

        var lines: [String] = []

        // Detect if this is a method (name contains ".", e.g. "Point.sum")
        let isMethod = function.name.contains(".")
        let className: String? = isMethod ? String(function.name.split(separator: ".").first!) : nil
        currentClassName = className

        // For the "main" function, use C ABI: i32 @main()
        let isMain = function.name == "main"
        isMainFunction = isMain

        // Infer actual return type (MIR may say .unit for methods that return values)
        let retType: String
        if isMain {
            retType = "i32"
        } else if function.returnType != .unit {
            retType = llvmType(function.returnType)
        } else {
            // Check if the function actually returns a value despite .unit declaration
            retType = inferActualReturnType(function)
        }

        currentReturnType = retType
        let funcName = llvmFunctionName(function.name)
        // Infer parameter types from usage (MIR lowering emits .unit for all params)
        let inferredParams = inferParamTypes(function)

        var paramList: [String] = []

        // Methods get an implicit `this` pointer as first parameter
        if isMethod {
            paramList.append("ptr %this")
        }

        for (name, type) in function.parameters {
            let lt: String
            if let inferred = inferredParams[name] {
                lt = inferred
            } else {
                let formal = llvmType(type)
                lt = formal != "void" ? formal : "i64"
            }
            let paramLLVM = "%param.\(name)"
            paramMap[name] = paramLLVM
            paramList.append("\(lt) \(paramLLVM)")
        }
        let params = paramList.joined(separator: ", ")

        lines.append("define \(retType) @\(funcName)(\(params)) {")

        // Alloca prologue block: emit allocas for all temps
        let allTemps = collectTemps(function)
        let hasAllocas = !allTemps.isEmpty || !function.parameters.isEmpty || isMethod
        let firstBlockLabel = function.blocks.first.map { llvmLabel($0.label) } ?? "body"

        if hasAllocas {
            lines.append("prologue:")

            // Store `this` pointer so it's accessible like a local
            if isMethod {
                lines.append("  %p.this = alloca ptr")
                lines.append("  store ptr %this, ptr %p.this")
                registerMap["this"] = "%p.this"
                registerTypes["this"] = "ptr"
            }

            // Allocas for parameters (so we can store/load them like locals)
            for (name, type) in function.parameters {
                let lt: String
                if let inferred = inferredParams[name] {
                    lt = inferred
                } else {
                    let formal = llvmType(type)
                    lt = formal != "void" ? formal : "i64"
                }
                let allocaName = "%p.\(name)"
                registerMap["param.\(name)"] = allocaName
                registerTypes["param.\(name)"] = lt
                lines.append("  \(allocaName) = alloca \(lt)")
                lines.append("  store \(lt) %param.\(name), ptr \(allocaName)")
            }
            // Allocas for MIR temps
            for (temp, type) in allTemps {
                let lt = type
                let rawName = temp.hasPrefix("%") ? String(temp.dropFirst()) : temp
                let allocaName = "%\(rawName)"
                registerMap[temp] = allocaName
                registerTypes[temp] = lt
                lines.append("  \(allocaName) = alloca \(lt)")
            }
            // Jump to first MIR block
            lines.append("  br label %\(firstBlockLabel)")
        }

        // Pre-scan for try/catch blocks to record exception destinations
        catchBlocks = [:]
        for block in function.blocks {
            for inst in block.instructions {
                if case .tryBegin(let catchLabel, let excDest) = inst {
                    catchBlocks[catchLabel] = excDest
                }
            }
        }

        // Emit basic blocks
        for block in function.blocks {
            lines.append("\(llvmLabel(block.label)):")

            // If this is a catch block, inject exception value retrieval
            // Note: rockit_exc_throw already popped the frame, so no pop here
            if let excDest = catchBlocks[block.label] {
                let excRaw = nextSSA()
                lines.append("  \(excRaw) = call i64 @rockit_exc_get()")
                // Convert i64 to the exception dest's type
                let excType = typeOf(excDest)
                if excType == "ptr" {
                    let castTmp = nextSSA()
                    lines.append("  \(castTmp) = inttoptr i64 \(excRaw) to ptr")
                    lines.append("  " + storeToTemp(excDest, value: castTmp, type: "ptr"))
                } else {
                    lines.append("  " + storeToTemp(excDest, value: excRaw, type: "i64"))
                }
            }

            for inst in block.instructions {
                let emitted = emitInstruction(inst)
                for line in emitted {
                    lines.append("  \(line)")
                }
            }
            if let term = block.terminator {
                let emitted = emitTerminator(term, returnType: function.returnType)
                for line in emitted {
                    lines.append("  \(line)")
                }
            }
        }

        lines.append("}")
        return lines.joined(separator: "\n")
    }

    // MARK: - Return Type Inference

    /// Infer actual return type for functions that declare `.unit` but return a value.
    /// MIR lowering in Stage 0 sometimes emits `.unit` for methods that return values.
    private func inferActualReturnType(_ function: MIRFunction) -> String {
        // Look at ret terminators — if any return a value, infer the type
        for block in function.blocks {
            if case .ret(let val) = block.terminator, let val = val {
                // The ret value is a temp — figure out its type from the instructions
                for b in function.blocks {
                    for inst in b.instructions {
                        switch inst {
                        case .add(let d, _, _, let t) where d == val:
                            if case .string = t { return "ptr" }
                            return llvmArithType(t)
                        case .sub(let d, _, _, let t) where d == val,
                             .mul(let d, _, _, let t) where d == val,
                             .div(let d, _, _, let t) where d == val,
                             .mod(let d, _, _, let t) where d == val:
                            return llvmArithType(t)
                        case .neg(let d, _, let t) where d == val:
                            return llvmArithType(t)
                        case .eq(let d, _, _, _) where d == val,
                             .neq(let d, _, _, _) where d == val,
                             .lt(let d, _, _, _) where d == val,
                             .lte(let d, _, _, _) where d == val,
                             .gt(let d, _, _, _) where d == val,
                             .gte(let d, _, _, _) where d == val,
                             .and(let d, _, _) where d == val,
                             .or(let d, _, _) where d == val,
                             .not(let d, _) where d == val:
                            return "i1"
                        case .constInt(let d, _) where d == val:
                            return "i64"
                        case .constFloat(let d, _) where d == val:
                            return "double"
                        case .constBool(let d, _) where d == val:
                            return "i1"
                        case .constString(let d, _) where d == val,
                             .constNull(let d) where d == val,
                             .stringConcat(let d, _) where d == val,
                             .newObject(let d, _, _) where d == val:
                            return "ptr"
                        case .getField(let d, _, _) where d == val:
                            return "i64"  // Default; could look up field type
                        case .call(let d, let fn, _) where d == val:
                            return inferCallReturnType(fn)
                        default:
                            break
                        }
                    }
                }
                // If the ret value comes from a load, trace it
                return "i64"  // Default for methods returning values
            }
        }
        return "void"
    }

    // MARK: - Parameter Type Inference

    /// Infer actual parameter types by analyzing how they're used in the function body.
    /// MIR lowering in Stage 0 emits all params as `.unit`, so we need this.
    private func inferParamTypes(_ function: MIRFunction) -> [String: String] {
        var inferred: [String: String] = [:]
        let originMap = buildParamOriginMap(function)

        for block in function.blocks {
            for inst in block.instructions {
                switch inst {
                // If a param-loaded value feeds into arithmetic, infer its type
                case .add(_, let l, let r, let t), .sub(_, let l, let r, let t),
                     .mul(_, let l, let r, let t), .div(_, let l, let r, let t),
                     .mod(_, let l, let r, let t):
                    // For string +, MIR uses .string type on the add instruction
                    let lt: String
                    switch t {
                    case .string: lt = "ptr"
                    default: lt = llvmArithType(t)
                    }
                    inferParamFromOperand(l, type: lt, originMap: originMap, inferred: &inferred)
                    inferParamFromOperand(r, type: lt, originMap: originMap, inferred: &inferred)
                case .neg(_, let o, let t):
                    inferParamFromOperand(o, type: llvmArithType(t), originMap: originMap, inferred: &inferred)
                case .eq(_, let l, let r, let t), .neq(_, let l, let r, let t),
                     .lt(_, let l, let r, let t), .lte(_, let l, let r, let t),
                     .gt(_, let l, let r, let t), .gte(_, let l, let r, let t):
                    let lt = llvmArithType(t)
                    inferParamFromOperand(l, type: lt, originMap: originMap, inferred: &inferred)
                    inferParamFromOperand(r, type: lt, originMap: originMap, inferred: &inferred)
                case .stringConcat(_, let parts):
                    for part in parts {
                        inferParamFromOperand(part, type: "ptr", originMap: originMap, inferred: &inferred)
                    }
                case .call(_, _, _):
                    break
                default:
                    break
                }
            }
        }

        // If return type is known and a param feeds into a return, infer from return type
        let retType = llvmType(function.returnType)
        if retType != "void" {
            for block in function.blocks {
                if case .ret(let val) = block.terminator, let val = val {
                    inferParamFromOperand(val, type: retType, originMap: originMap, inferred: &inferred)
                }
            }
        }

        return inferred
    }

    /// Build a reverse map: for each temp, what param (if any) does its value come from?
    /// Traces through load/store chains.
    private func buildParamOriginMap(_ function: MIRFunction) -> [String: String] {
        // Map from temp → param name it originates from
        var origin: [String: String] = [:]

        // First, find direct param loads
        for block in function.blocks {
            for inst in block.instructions {
                if case .load(let dest, let src) = inst, src.hasPrefix("param.") {
                    let paramName = String(src.dropFirst(6))
                    origin[dest] = paramName
                }
            }
        }

        // Propagate through store/load chains
        // store SLOT, SRC → if SRC has origin, SLOT gets same origin
        // load DEST, SLOT → if SLOT has origin, DEST gets same origin
        var changed = true
        while changed {
            changed = false
            for block in function.blocks {
                for inst in block.instructions {
                    switch inst {
                    case .store(let dest, let src):
                        if let paramName = origin[src], origin[dest] == nil {
                            origin[dest] = paramName
                            changed = true
                        }
                    case .load(let dest, let src):
                        if !src.hasPrefix("param."), let paramName = origin[src], origin[dest] == nil {
                            origin[dest] = paramName
                            changed = true
                        }
                    default:
                        break
                    }
                }
            }
        }

        return origin
    }

    /// Given an operand temp, trace back through loads/stores to find if it originates
    /// from a parameter, and if so, infer that parameter's type.
    private func inferParamFromOperand(_ operand: String, type: String, originMap: [String: String], inferred: inout [String: String]) {
        if let paramName = originMap[operand] {
            // Don't override a more specific type
            if inferred[paramName] == nil {
                inferred[paramName] = type
            }
        }
    }

    // MARK: - Temp Collection

    /// Collect all temps and infer their LLVM types from usage context.
    /// Two-pass: first infer direct types, then propagate through store/load chains.
    private func collectTemps(_ function: MIRFunction) -> [(String, String)] {
        var tempTypes: [String: String] = [:]
        // Track store relationships: dest ← src
        var storeEdges: [(dest: String, src: String)] = []
        // Inferred parameter types
        let inferredParams = inferParamTypes(function)

        // Pass 1: Direct type inference
        for block in function.blocks {
            for inst in block.instructions {
                switch inst {
                case .constInt(let d, _):
                    tempTypes[d] = "i64"
                case .constFloat(let d, _):
                    tempTypes[d] = "double"
                case .constBool(let d, _):
                    tempTypes[d] = "i1"
                case .constString(let d, _):
                    tempTypes[d] = "ptr"
                case .constNull(let d):
                    tempTypes[d] = "ptr"
                case .alloc(let d, let type):
                    let lt = llvmType(type)
                    // Don't assign void — we'll infer from stores in pass 2
                    if lt != "void" {
                        tempTypes[d] = lt
                    }
                case .load(let d, let src):
                    // Inherit type from source
                    if src.hasPrefix("global."), function.name.contains(".") {
                        // Method field access: global.x → field type
                        let fieldName = String(src.dropFirst(7))
                        let className = String(function.name.split(separator: ".").first!)
                        tempTypes[d] = fieldType(typeName: className, fieldName: fieldName)
                    } else if src.hasPrefix("param.") {
                        let paramName = String(src.dropFirst(6))
                        // Use inferred type first, then formal type, then default
                        if let inferred = inferredParams[paramName] {
                            tempTypes[d] = inferred
                        } else if let pt = function.parameters.first(where: { $0.0 == paramName }) {
                            let lt = llvmType(pt.1)
                            tempTypes[d] = lt != "void" ? lt : "i64"
                        } else {
                            tempTypes[d] = "i64"
                        }
                    } else if let srcType = tempTypes[src] {
                        if srcType != "void" {
                            tempTypes[d] = srcType
                        }
                    }
                    // Also record as an edge for pass 2
                    storeEdges.append((dest: d, src: src))
                case .store(let dest, let src):
                    storeEdges.append((dest: dest, src: src))
                case .add(let d, _, _, let t), .sub(let d, _, _, let t),
                     .mul(let d, _, _, let t), .div(let d, _, _, let t),
                     .mod(let d, _, _, let t):
                    if case .string = t {
                        tempTypes[d] = "ptr"  // String add → string concat
                    } else {
                        tempTypes[d] = llvmArithType(t)
                    }
                case .neg(let d, _, let t):
                    tempTypes[d] = llvmArithType(t)
                case .eq(let d, _, _, _), .neq(let d, _, _, _),
                     .lt(let d, _, _, _), .lte(let d, _, _, _),
                     .gt(let d, _, _, _), .gte(let d, _, _, _):
                    tempTypes[d] = "i1"
                case .and(let d, _, _), .or(let d, _, _), .not(let d, _):
                    tempTypes[d] = "i1"
                case .call(let d, let function, _):
                    if let d = d {
                        tempTypes[d] = inferCallReturnType(function)
                    }
                case .callIndirect(let d, _, _):
                    if let d = d { tempTypes[d] = "i64" }
                case .virtualCall(let d, _, let method, _):
                    if let d = d {
                        let qualifiedMethod = resolveMethodName(method)
                        if let sig = functionSignatures[qualifiedMethod] {
                            let lt = llvmType(sig)
                            tempTypes[d] = lt != "void" ? lt : "i64"
                        } else {
                            tempTypes[d] = "i64"
                        }
                    }
                case .getField(let d, _, let fieldName):
                    // Try to infer field type from type declarations
                    // For now default to i64 (most fields are Int)
                    var resolved = false
                    for (_, decl) in typeDecls {
                        if let field = decl.fields.first(where: { $0.0 == fieldName }) {
                            let lt = llvmType(field.1)
                            tempTypes[d] = lt != "void" ? lt : "i64"
                            resolved = true
                            break
                        }
                    }
                    if !resolved { tempTypes[d] = "i64" }
                case .setField:
                    break
                case .newObject(let d, _, _):
                    tempTypes[d] = "ptr"
                case .nullCheck(let d, _):
                    tempTypes[d] = "ptr"
                case .isNull(let d, _):
                    tempTypes[d] = "i1"
                case .typeCheck(let d, _, _):
                    tempTypes[d] = "i1"
                case .typeCast(let d, _, _):
                    tempTypes[d] = "ptr"
                case .stringConcat(let d, _):
                    tempTypes[d] = "ptr"
                case .tryBegin(_, let d):
                    tempTypes[d] = "ptr"
                case .tryEnd:
                    break
                }
            }
        }

        // Pass 2: Propagate types through store/load edges
        // If `store %t0, %t1` and %t1 has type i64, then %t0 should also be i64.
        var changed = true
        while changed {
            changed = false
            for edge in storeEdges {
                if let srcType = tempTypes[edge.src], srcType != "void" {
                    if tempTypes[edge.dest] == nil || tempTypes[edge.dest] == "void" {
                        tempTypes[edge.dest] = srcType
                        changed = true
                    }
                }
                if let destType = tempTypes[edge.dest], destType != "void" {
                    if tempTypes[edge.src] == nil || tempTypes[edge.src] == "void" {
                        tempTypes[edge.src] = destType
                        changed = true
                    }
                }
            }
        }

        // Default any remaining untyped temps to i64
        for (key, value) in tempTypes {
            if value == "void" {
                tempTypes[key] = "i64"
            }
        }

        // Filter out parameter names (they get separate allocas in the prologue)
        let paramNames = Set(function.parameters.map { "param.\($0.0)" })

        // Return sorted for deterministic output, excluding param entries
        return tempTypes
            .filter { !paramNames.contains($0.key) }
            .sorted(by: { $0.key < $1.key })
    }

    // MARK: - Instruction Emission

    private func emitInstruction(_ inst: MIRInstruction) -> [String] {
        switch inst {
        case .constInt(let dest, let value):
            return [storeToTemp(dest, value: "\(value)", type: "i64")]

        case .constFloat(let dest, let value):
            let hexBits = String(value.bitPattern, radix: 16, uppercase: true)
            let llvmHex = "0x\(hexBits)"
            return [storeToTemp(dest, value: llvmHex, type: "double")]

        case .constBool(let dest, let value):
            return [storeToTemp(dest, value: value ? "1" : "0", type: "i1")]

        case .constString(let dest, let value):
            let globalName = stringPool[value]!
            let tmp = nextSSA()
            return [
                "\(tmp) = call ptr @rockit_string_new(ptr \(globalName))",
                storeToTemp(dest, value: tmp, type: "ptr")
            ]

        case .constNull(let dest):
            return [storeToTemp(dest, value: "null", type: "ptr")]

        case .alloc:
            // Allocas are emitted in the entry block; nothing to do here
            return []

        case .store(let dest, let src):
            let srcType = typeOf(src)
            let tmp = nextSSA()
            return [
                "\(tmp) = load \(srcType), ptr \(addrOf(src))",
                "store \(srcType) \(tmp), ptr \(addrOf(dest))"
            ]

        case .load(let dest, let src):
            // In methods, `load global.X` means field access on `this`
            if src.hasPrefix("global."), currentClassName != nil {
                let fieldName = String(src.dropFirst(7))  // "global.x" → "x"
                return emitGetField(dest: dest, object: "this", fieldName: fieldName)
            } else if src.hasPrefix("param.") || src.hasPrefix("global.") || src == "this" || src == "super" {
                let srcType = typeOf(dest)
                let tmp = nextSSA()
                return [
                    "\(tmp) = load \(srcType), ptr \(addrOf(src))",
                    "store \(srcType) \(tmp), ptr \(addrOf(dest))"
                ]
            } else {
                let srcType = typeOf(src)
                let tmp = nextSSA()
                return [
                    "\(tmp) = load \(srcType), ptr \(addrOf(src))",
                    "store \(srcType) \(tmp), ptr \(addrOf(dest))"
                ]
            }

        case .add(let dest, let lhs, let rhs, let type):
            // String + is lowered as MIR add with .string type — emit concat instead
            if case .string = type {
                return emitStringConcat(dest: dest, parts: [lhs, rhs])
            }
            return emitBinaryArith("add", "fadd", dest: dest, lhs: lhs, rhs: rhs, type: type)

        case .sub(let dest, let lhs, let rhs, let type):
            return emitBinaryArith("sub", "fsub", dest: dest, lhs: lhs, rhs: rhs, type: type)

        case .mul(let dest, let lhs, let rhs, let type):
            return emitBinaryArith("mul", "fmul", dest: dest, lhs: lhs, rhs: rhs, type: type)

        case .div(let dest, let lhs, let rhs, let type):
            return emitBinaryArith("sdiv", "fdiv", dest: dest, lhs: lhs, rhs: rhs, type: type)

        case .mod(let dest, let lhs, let rhs, let type):
            return emitBinaryArith("srem", "frem", dest: dest, lhs: lhs, rhs: rhs, type: type)

        case .neg(let dest, let operand, let type):
            let lt = llvmArithType(type)
            let tmp1 = nextSSA()
            let tmp2 = nextSSA()
            if isFloatType(type) {
                return [
                    "\(tmp1) = load \(lt), ptr \(addrOf(operand))",
                    "\(tmp2) = fneg \(lt) \(tmp1)",
                    storeToTemp(dest, value: tmp2, type: lt)
                ]
            } else {
                return [
                    "\(tmp1) = load \(lt), ptr \(addrOf(operand))",
                    "\(tmp2) = sub \(lt) 0, \(tmp1)",
                    storeToTemp(dest, value: tmp2, type: lt)
                ]
            }

        case .eq(let dest, let lhs, let rhs, let type):
            return emitComparison("icmp eq", "fcmp oeq", dest: dest, lhs: lhs, rhs: rhs, type: type)
        case .neq(let dest, let lhs, let rhs, let type):
            return emitComparison("icmp ne", "fcmp one", dest: dest, lhs: lhs, rhs: rhs, type: type)
        case .lt(let dest, let lhs, let rhs, let type):
            return emitComparison("icmp slt", "fcmp olt", dest: dest, lhs: lhs, rhs: rhs, type: type)
        case .lte(let dest, let lhs, let rhs, let type):
            return emitComparison("icmp sle", "fcmp ole", dest: dest, lhs: lhs, rhs: rhs, type: type)
        case .gt(let dest, let lhs, let rhs, let type):
            return emitComparison("icmp sgt", "fcmp ogt", dest: dest, lhs: lhs, rhs: rhs, type: type)
        case .gte(let dest, let lhs, let rhs, let type):
            return emitComparison("icmp sge", "fcmp oge", dest: dest, lhs: lhs, rhs: rhs, type: type)

        case .and(let dest, let lhs, let rhs):
            let tmp1 = nextSSA()
            let tmp2 = nextSSA()
            let tmp3 = nextSSA()
            return [
                "\(tmp1) = load i1, ptr \(addrOf(lhs))",
                "\(tmp2) = load i1, ptr \(addrOf(rhs))",
                "\(tmp3) = and i1 \(tmp1), \(tmp2)",
                storeToTemp(dest, value: tmp3, type: "i1")
            ]

        case .or(let dest, let lhs, let rhs):
            let tmp1 = nextSSA()
            let tmp2 = nextSSA()
            let tmp3 = nextSSA()
            return [
                "\(tmp1) = load i1, ptr \(addrOf(lhs))",
                "\(tmp2) = load i1, ptr \(addrOf(rhs))",
                "\(tmp3) = or i1 \(tmp1), \(tmp2)",
                storeToTemp(dest, value: tmp3, type: "i1")
            ]

        case .not(let dest, let operand):
            let tmp1 = nextSSA()
            let tmp2 = nextSSA()
            return [
                "\(tmp1) = load i1, ptr \(addrOf(operand))",
                "\(tmp2) = xor i1 \(tmp1), 1",
                storeToTemp(dest, value: tmp2, type: "i1")
            ]

        case .call(let dest, let function, let args):
            return emitCall(dest: dest, function: function, args: args)

        case .virtualCall(let dest, let object, let method, let args):
            // For now, static dispatch: call @TypeName.methodName(obj, args...)
            return emitVirtualCall(dest: dest, object: object, method: method, args: args)

        case .callIndirect(let dest, let functionRef, let args):
            // Load function pointer and call
            let ptrTmp = nextSSA()
            var lines: [String] = [
                "\(ptrTmp) = load ptr, ptr \(addrOf(functionRef))"
            ]
            var argStrs: [String] = []
            for arg in args {
                let argType = typeOf(arg)
                let tmp = nextSSA()
                lines.append("\(tmp) = load \(argType), ptr \(addrOf(arg))")
                argStrs.append("\(argType) \(tmp)")
            }
            let argList = argStrs.joined(separator: ", ")
            if let dest = dest {
                let retType = typeOf(dest)
                let resultTmp = nextSSA()
                lines.append("\(resultTmp) = call \(retType) \(ptrTmp)(\(argList))")
                lines.append(storeToTemp(dest, value: resultTmp, type: retType))
            } else {
                lines.append("call void \(ptrTmp)(\(argList))")
            }
            return lines

        case .getField(let dest, let object, let fieldName):
            return emitGetField(dest: dest, object: object, fieldName: fieldName)

        case .setField(let object, let fieldName, let value):
            return emitSetField(object: object, fieldName: fieldName, value: value)

        case .newObject(let dest, let typeName, let args):
            return emitNewObject(dest: dest, typeName: typeName, args: args)

        case .nullCheck(let dest, let operand):
            let tmp1 = nextSSA()
            let tmp2 = nextSSA()
            let labelOk = "nullcheck.ok.\(ssaCounter)"
            let labelFail = "nullcheck.fail.\(ssaCounter)"
            ssaCounter += 1
            return [
                "\(tmp1) = load ptr, ptr \(addrOf(operand))",
                "\(tmp2) = icmp eq ptr \(tmp1), null",
                "br i1 \(tmp2), label %\(labelFail), label %\(labelOk)",
                "",
                "\(labelFail):",
                "  call void @rockit_panic(ptr @.str.nullcheck)",
                "  unreachable",
                "",
                "\(labelOk):",
                storeToTemp(dest, value: tmp1, type: "ptr")
            ]

        case .isNull(let dest, let operand):
            let tmp1 = nextSSA()
            let tmp2 = nextSSA()
            return [
                "\(tmp1) = load ptr, ptr \(addrOf(operand))",
                "\(tmp2) = icmp eq ptr \(tmp1), null",
                storeToTemp(dest, value: tmp2, type: "i1")
            ]

        case .typeCheck(let dest, _, _):
            // TODO: Phase 1E
            return [storeToTemp(dest, value: "0", type: "i1")]

        case .typeCast(let dest, let operand, _):
            // TODO: Phase 1E — passthrough for now
            let tmp = nextSSA()
            return [
                "\(tmp) = load ptr, ptr \(addrOf(operand))",
                storeToTemp(dest, value: tmp, type: "ptr")
            ]

        case .stringConcat(let dest, let parts):
            return emitStringConcat(dest: dest, parts: parts)

        case .tryBegin(let catchLabel, _):
            // Push exception frame, call _setjmp, branch on result
            let bufTmp = nextSSA()
            let jmpRet = nextSSA()
            let caught = nextSSA()
            let tryBodyLabel = "try.body.\(ssaCounter)"
            ssaCounter += 1
            return [
                "\(bufTmp) = call ptr @rockit_exc_push()",
                "\(jmpRet) = call i32 @_setjmp(ptr \(bufTmp)) #0",
                "\(caught) = icmp ne i32 \(jmpRet), 0",
                "br i1 \(caught), label %\(llvmLabel(catchLabel)), label %\(tryBodyLabel)",
                "",
                "\(tryBodyLabel):"
            ]
        case .tryEnd:
            return ["call void @rockit_exc_pop()"]
        }
    }

    // MARK: - Terminator Emission

    /// Whether the function currently being emitted is the entry point.
    private var isMainFunction = false

    /// Actual LLVM return type for the current function (may differ from MIR's declared type).
    private var currentReturnType: String = "void"

    private func emitTerminator(_ term: MIRTerminator, returnType: MIRType) -> [String] {
        switch term {
        case .ret(let val):
            if isMainFunction {
                // C ABI: main returns i32 0
                return ["ret i32 0"]
            }
            if let val = val {
                // Use the function's actual return type (may be inferred, not MIR's declared type)
                let retLLVM = currentReturnType != "void" ? currentReturnType : typeOf(val)
                let tmp = nextSSA()
                return [
                    "\(tmp) = load \(retLLVM), ptr \(addrOf(val))",
                    "ret \(retLLVM) \(tmp)"
                ]
            } else {
                return ["ret void"]
            }

        case .jump(let label):
            return ["br label %\(llvmLabel(label))"]

        case .branch(let condition, let thenLabel, let elseLabel):
            let tmp = nextSSA()
            return [
                "\(tmp) = load i1, ptr \(addrOf(condition))",
                "br i1 \(tmp), label %\(llvmLabel(thenLabel)), label %\(llvmLabel(elseLabel))"
            ]

        case .throwValue(let val):
            // Convert the thrown value to i64 and call rockit_exc_throw
            let valType = typeOf(val)
            let valTmp = nextSSA()
            var lines: [String] = [
                "\(valTmp) = load \(valType), ptr \(addrOf(val))"
            ]
            if valType == "ptr" {
                let castTmp = nextSSA()
                lines.append("\(castTmp) = ptrtoint ptr \(valTmp) to i64")
                lines.append("call void @rockit_exc_throw(i64 \(castTmp))")
            } else if valType == "i1" {
                let extTmp = nextSSA()
                lines.append("\(extTmp) = zext i1 \(valTmp) to i64")
                lines.append("call void @rockit_exc_throw(i64 \(extTmp))")
            } else {
                lines.append("call void @rockit_exc_throw(i64 \(valTmp))")
            }
            lines.append("unreachable")
            return lines

        case .unreachable:
            return ["unreachable"]
        }
    }

    // MARK: - Binary Arithmetic Helper

    private func emitBinaryArith(
        _ intOp: String, _ floatOp: String,
        dest: String, lhs: String, rhs: String, type: MIRType
    ) -> [String] {
        let lt = llvmArithType(type)
        let tmp1 = nextSSA()
        let tmp2 = nextSSA()
        let tmp3 = nextSSA()
        let op = isFloatType(type) ? floatOp : intOp
        return [
            "\(tmp1) = load \(lt), ptr \(addrOf(lhs))",
            "\(tmp2) = load \(lt), ptr \(addrOf(rhs))",
            "\(tmp3) = \(op) \(lt) \(tmp1), \(tmp2)",
            storeToTemp(dest, value: tmp3, type: lt)
        ]
    }

    // MARK: - Comparison Helper

    private func emitComparison(
        _ intCmp: String, _ floatCmp: String,
        dest: String, lhs: String, rhs: String, type: MIRType
    ) -> [String] {
        let lt = llvmArithType(type)
        let tmp1 = nextSSA()
        let tmp2 = nextSSA()
        let tmp3 = nextSSA()
        let cmp = isFloatType(type) ? floatCmp : intCmp
        return [
            "\(tmp1) = load \(lt), ptr \(addrOf(lhs))",
            "\(tmp2) = load \(lt), ptr \(addrOf(rhs))",
            "\(tmp3) = \(cmp) \(lt) \(tmp1), \(tmp2)",
            storeToTemp(dest, value: tmp3, type: "i1")
        ]
    }

    // MARK: - Call Emission

    private func emitCall(dest: String?, function: String, args: [String]) -> [String] {
        // Special handling for builtins
        if function == "println" || function == "print" {
            return emitPrintCall(function: function, args: args)
        }
        if function == "toString" {
            return emitToStringCall(dest: dest, args: args)
        }
        if function == "listOf" {
            return emitListOf(dest: dest, args: args)
        }
        if function == "mapOf" {
            return emitMapOf(dest: dest, args: args)
        }
        if function == "mutableListOf" {
            return emitListOf(dest: dest, args: args)
        }
        if function == "mutableMapOf" {
            return emitMapOf(dest: dest, args: args)
        }

        var lines: [String] = []
        var argStrs: [String] = []
        for arg in args {
            let argType = typeOf(arg)
            let tmp = nextSSA()
            lines.append("\(tmp) = load \(argType), ptr \(addrOf(arg))")
            argStrs.append("\(argType) \(tmp)")
        }

        let argList = argStrs.joined(separator: ", ")
        let funcName = llvmFunctionName(function)

        if let dest = dest {
            let retType = typeOf(dest)
            let resultTmp = nextSSA()
            lines.append("\(resultTmp) = call \(retType) @\(funcName)(\(argList))")
            lines.append(storeToTemp(dest, value: resultTmp, type: retType))
        } else {
            lines.append("call void @\(funcName)(\(argList))")
        }

        return lines
    }

    // MARK: - Collection Builtins

    private func emitListOf(dest: String?, args: [String]) -> [String] {
        guard let dest = dest else { return [] }
        var lines: [String] = []
        let listTmp = nextSSA()
        lines.append("\(listTmp) = call ptr @rockit_list_create()")
        for arg in args {
            let argType = typeOf(arg)
            let valTmp = nextSSA()
            lines.append("\(valTmp) = load \(argType), ptr \(addrOf(arg))")
            // Convert to i64 for storage
            if argType == "ptr" {
                let castTmp = nextSSA()
                lines.append("\(castTmp) = ptrtoint ptr \(valTmp) to i64")
                lines.append("call void @rockit_list_append(ptr \(listTmp), i64 \(castTmp))")
            } else if argType == "i1" {
                let extTmp = nextSSA()
                lines.append("\(extTmp) = zext i1 \(valTmp) to i64")
                lines.append("call void @rockit_list_append(ptr \(listTmp), i64 \(extTmp))")
            } else if argType == "double" {
                let castTmp = nextSSA()
                lines.append("\(castTmp) = bitcast double \(valTmp) to i64")
                lines.append("call void @rockit_list_append(ptr \(listTmp), i64 \(castTmp))")
            } else {
                lines.append("call void @rockit_list_append(ptr \(listTmp), i64 \(valTmp))")
            }
        }
        lines.append(storeToTemp(dest, value: listTmp, type: "ptr"))
        return lines
    }

    private func emitMapOf(dest: String?, args: [String]) -> [String] {
        guard let dest = dest else { return [] }
        var lines: [String] = []
        let mapTmp = nextSSA()
        lines.append("\(mapTmp) = call ptr @rockit_map_create()")
        // mapOf takes pairs: key1, val1, key2, val2, ...
        var i = 0
        while i + 1 < args.count {
            let keyTmp = nextSSA()
            let valTmp = nextSSA()
            lines.append("\(keyTmp) = load i64, ptr \(addrOf(args[i]))")
            lines.append("\(valTmp) = load i64, ptr \(addrOf(args[i+1]))")
            lines.append("call void @rockit_map_put(ptr \(mapTmp), i64 \(keyTmp), i64 \(valTmp))")
            i += 2
        }
        lines.append(storeToTemp(dest, value: mapTmp, type: "ptr"))
        return lines
    }

    // MARK: - Print Builtin

    private func emitPrintCall(function: String, args: [String]) -> [String] {
        guard let arg = args.first else {
            return ["call void @rockit_println_null()"]
        }

        let argType = typeOf(arg)
        let tmp = nextSSA()
        let prefix = function == "println" ? "rockit_println" : "rockit_print"

        switch argType {
        case "i64":
            return [
                "\(tmp) = load i64, ptr \(addrOf(arg))",
                "call void @\(prefix)_int(i64 \(tmp))"
            ]
        case "double":
            return [
                "\(tmp) = load double, ptr \(addrOf(arg))",
                "call void @\(prefix)_float(double \(tmp))"
            ]
        case "i1":
            return [
                "\(tmp) = load i1, ptr \(addrOf(arg))",
                "call void @\(prefix)_bool(i1 \(tmp))"
            ]
        case "ptr":
            return [
                "\(tmp) = load ptr, ptr \(addrOf(arg))",
                "call void @\(prefix)_string(ptr \(tmp))"
            ]
        default:
            return [
                "\(tmp) = load i64, ptr \(addrOf(arg))",
                "call void @\(prefix)_int(i64 \(tmp))"
            ]
        }
    }

    // MARK: - toString Builtin

    private func emitToStringCall(dest: String?, args: [String]) -> [String] {
        guard let dest = dest, let arg = args.first else { return [] }

        let argType = typeOf(arg)
        let tmp = nextSSA()
        let resultTmp = nextSSA()

        switch argType {
        case "i64":
            return [
                "\(tmp) = load i64, ptr \(addrOf(arg))",
                "\(resultTmp) = call ptr @rockit_int_to_string(i64 \(tmp))",
                storeToTemp(dest, value: resultTmp, type: "ptr")
            ]
        case "double":
            return [
                "\(tmp) = load double, ptr \(addrOf(arg))",
                "\(resultTmp) = call ptr @rockit_float_to_string(double \(tmp))",
                storeToTemp(dest, value: resultTmp, type: "ptr")
            ]
        case "i1":
            return [
                "\(tmp) = load i1, ptr \(addrOf(arg))",
                "\(resultTmp) = call ptr @rockit_bool_to_string(i1 \(tmp))",
                storeToTemp(dest, value: resultTmp, type: "ptr")
            ]
        case "ptr":
            // Already a string pointer — just copy
            return [
                "\(tmp) = load ptr, ptr \(addrOf(arg))",
                storeToTemp(dest, value: tmp, type: "ptr")
            ]
        default:
            return [
                "\(tmp) = load i64, ptr \(addrOf(arg))",
                "\(resultTmp) = call ptr @rockit_int_to_string(i64 \(tmp))",
                storeToTemp(dest, value: resultTmp, type: "ptr")
            ]
        }
    }

    // MARK: - Virtual Call

    /// Resolve a method name to its fully-qualified name (e.g., "sum" → "Point.sum")
    /// by searching the type declarations for a matching method.
    private func resolveMethodName(_ method: String) -> String {
        // If already qualified (contains "."), use as-is
        if method.contains(".") { return method }
        // Search type declarations for a method matching this name
        for (typeName, decl) in typeDecls {
            if decl.methods.contains("\(typeName).\(method)") {
                return "\(typeName).\(method)"
            }
        }
        return method
    }

    /// Check if a method is a known collection builtin and emit the C runtime call directly.
    private func emitCollectionMethod(dest: String?, object: String, method: String, args: [String]) -> [String]? {
        // Map method names to C runtime functions
        let methodMap: [String: (cName: String, retType: String)] = [
            "size":        ("rockit_list_size",     "i64"),
            "get":         ("rockit_list_get",      "i64"),
            "set":         ("rockit_list_set",      "void"),
            "add":         ("rockit_list_append",   "void"),
            "isEmpty":     ("rockit_list_is_empty", "i1"),
            "containsKey": ("rockit_map_contains_key", "i1"),
            "put":         ("rockit_map_put",       "void"),
        ]

        guard let info = methodMap[method] else { return nil }

        var lines: [String] = []
        let objTmp = nextSSA()
        lines.append("\(objTmp) = load ptr, ptr \(addrOf(object))")

        var argParts: [String] = ["ptr \(objTmp)"]
        for arg in args {
            let argType = typeOf(arg)
            let tmp = nextSSA()
            lines.append("\(tmp) = load \(argType), ptr \(addrOf(arg))")
            if argType == "ptr" {
                let castTmp = nextSSA()
                lines.append("\(castTmp) = ptrtoint ptr \(tmp) to i64")
                argParts.append("i64 \(castTmp)")
            } else if argType == "i1" {
                let extTmp = nextSSA()
                lines.append("\(extTmp) = zext i1 \(tmp) to i64")
                argParts.append("i64 \(extTmp)")
            } else {
                argParts.append("i64 \(tmp)")
            }
        }

        let argList = argParts.joined(separator: ", ")
        if let dest = dest, info.retType != "void" {
            let resultTmp = nextSSA()
            lines.append("\(resultTmp) = call \(info.retType) @\(info.cName)(\(argList))")
            lines.append(storeToTemp(dest, value: resultTmp, type: info.retType))
        } else {
            lines.append("call void @\(info.cName)(\(argList))")
        }

        return lines
    }

    private func emitVirtualCall(dest: String?, object: String, method: String, args: [String]) -> [String] {
        // Try collection method dispatch first
        if let result = emitCollectionMethod(dest: dest, object: object, method: method, args: args) {
            return result
        }

        // Static dispatch: resolve method to qualified name and call with `this` as first arg
        var lines: [String] = []
        var argStrs: [String] = []

        // Object pointer is the implicit `this` parameter
        let objTmp = nextSSA()
        lines.append("\(objTmp) = load ptr, ptr \(addrOf(object))")
        argStrs.append("ptr \(objTmp)")

        for arg in args {
            let argType = typeOf(arg)
            let tmp = nextSSA()
            lines.append("\(tmp) = load \(argType), ptr \(addrOf(arg))")
            argStrs.append("\(argType) \(tmp)")
        }

        let argList = argStrs.joined(separator: ", ")
        let qualifiedMethod = resolveMethodName(method)
        let funcName = llvmFunctionName(qualifiedMethod)

        if let dest = dest {
            // Look up the method's return type from function signatures
            let retType: String
            if let sig = functionSignatures[qualifiedMethod] {
                let lt = llvmType(sig)
                retType = lt != "void" ? lt : typeOf(dest)
            } else {
                retType = typeOf(dest)
            }
            let resultTmp = nextSSA()
            lines.append("\(resultTmp) = call \(retType) @\(funcName)(\(argList))")
            lines.append(storeToTemp(dest, value: resultTmp, type: retType))
        } else {
            lines.append("call void @\(funcName)(\(argList))")
        }

        return lines
    }

    // MARK: - String Concat

    private func emitStringConcat(dest: String, parts: [String]) -> [String] {
        guard !parts.isEmpty else {
            return [storeToTemp(dest, value: "null", type: "ptr")]
        }
        if parts.count == 1 {
            let tmp = nextSSA()
            return [
                "\(tmp) = load ptr, ptr \(addrOf(parts[0]))",
                storeToTemp(dest, value: tmp, type: "ptr")
            ]
        }

        var lines: [String] = []
        let first = nextSSA()
        lines.append("\(first) = load ptr, ptr \(addrOf(parts[0]))")
        var accumulator = first

        for i in 1..<parts.count {
            let next = nextSSA()
            lines.append("\(next) = load ptr, ptr \(addrOf(parts[i]))")
            let result = nextSSA()
            lines.append("\(result) = call ptr @rockit_string_concat(ptr \(accumulator), ptr \(next))")
            accumulator = result
        }

        lines.append(storeToTemp(dest, value: accumulator, type: "ptr"))
        return lines
    }

    // MARK: - Object Operations

    /// Look up field index from type declarations.
    private func fieldIndex(typeName: String, fieldName: String) -> Int? {
        guard let typeDecl = typeDecls[typeName] else { return nil }
        return typeDecl.fields.firstIndex(where: { $0.0 == fieldName })
    }

    /// Look up field type from type declarations.
    private func fieldType(typeName: String, fieldName: String) -> String {
        guard let typeDecl = typeDecls[typeName] else { return "i64" }
        if let field = typeDecl.fields.first(where: { $0.0 == fieldName }) {
            let lt = llvmType(field.1)
            return lt != "void" ? lt : "i64"
        }
        return "i64"
    }

    /// Determine the class name for an object temp by looking at newObject instructions.
    private func classNameForObject(_ temp: String) -> String? {
        // This is set during emitFunction processing
        // For `this` in methods, use currentClassName
        if temp == "this" {
            return currentClassName
        }
        return nil
    }

    private func emitNewObject(dest: String, typeName: String, args: [String]) -> [String] {
        var lines: [String] = []
        let typeNameGlobal = typeNamePool[typeName] ?? internTypeName(typeName)
        let fieldCount = typeDecls[typeName]?.fields.count ?? args.count

        // Allocate the object
        let objTmp = nextSSA()
        lines.append("\(objTmp) = call ptr @rockit_object_alloc(ptr \(typeNameGlobal), i32 \(fieldCount))")

        // Set each field from the constructor args
        if typeDecls[typeName] != nil {
            for (i, arg) in args.enumerated() {
                let argType = typeOf(arg)
                let valTmp = nextSSA()
                lines.append("\(valTmp) = load \(argType), ptr \(addrOf(arg))")
                if argType == "ptr" {
                    // Convert ptr to i64 for storage
                    let castTmp = nextSSA()
                    lines.append("\(castTmp) = ptrtoint ptr \(valTmp) to i64")
                    lines.append("call void @rockit_object_set_field(ptr \(objTmp), i32 \(i), i64 \(castTmp))")
                } else if argType == "i1" {
                    let extTmp = nextSSA()
                    lines.append("\(extTmp) = zext i1 \(valTmp) to i64")
                    lines.append("call void @rockit_object_set_field(ptr \(objTmp), i32 \(i), i64 \(extTmp))")
                } else if argType == "double" {
                    let castTmp = nextSSA()
                    lines.append("\(castTmp) = bitcast double \(valTmp) to i64")
                    lines.append("call void @rockit_object_set_field(ptr \(objTmp), i32 \(i), i64 \(castTmp))")
                } else {
                    // i64 — store directly
                    lines.append("call void @rockit_object_set_field(ptr \(objTmp), i32 \(i), i64 \(valTmp))")
                }
            }
        } else {
            // No type decl — store args by index
            for (i, arg) in args.enumerated() {
                let valTmp = nextSSA()
                lines.append("\(valTmp) = load i64, ptr \(addrOf(arg))")
                lines.append("call void @rockit_object_set_field(ptr \(objTmp), i32 \(i), i64 \(valTmp))")
            }
        }

        lines.append(storeToTemp(dest, value: objTmp, type: "ptr"))
        return lines
    }

    private func emitGetField(dest: String, object: String, fieldName: String) -> [String] {
        var lines: [String] = []

        // Load the object pointer
        let objTmp = nextSSA()
        lines.append("\(objTmp) = load ptr, ptr \(addrOf(object))")

        // Determine field index
        // Try currentClassName for method context, otherwise scan typeDecls
        let idx: Int
        if let cn = currentClassName, let i = fieldIndex(typeName: cn, fieldName: fieldName) {
            idx = i
        } else {
            // Search all type decls for this field
            var found: Int? = nil
            for (_, decl) in typeDecls {
                if let i = decl.fields.firstIndex(where: { $0.0 == fieldName }) {
                    found = i
                    break
                }
            }
            idx = found ?? 0
        }

        // Call get_field — returns i64
        let rawTmp = nextSSA()
        lines.append("\(rawTmp) = call i64 @rockit_object_get_field(ptr \(objTmp), i32 \(idx))")

        // Convert to the dest's expected type
        let destType = typeOf(dest)
        if destType == "ptr" {
            let castTmp = nextSSA()
            lines.append("\(castTmp) = inttoptr i64 \(rawTmp) to ptr")
            lines.append(storeToTemp(dest, value: castTmp, type: "ptr"))
        } else if destType == "i1" {
            let castTmp = nextSSA()
            lines.append("\(castTmp) = trunc i64 \(rawTmp) to i1")
            lines.append(storeToTemp(dest, value: castTmp, type: "i1"))
        } else if destType == "double" {
            let castTmp = nextSSA()
            lines.append("\(castTmp) = bitcast i64 \(rawTmp) to double")
            lines.append(storeToTemp(dest, value: castTmp, type: "double"))
        } else {
            // i64 — use directly
            lines.append(storeToTemp(dest, value: rawTmp, type: "i64"))
        }

        return lines
    }

    private func emitSetField(object: String, fieldName: String, value: String) -> [String] {
        var lines: [String] = []

        // Load the object pointer
        let objTmp = nextSSA()
        lines.append("\(objTmp) = load ptr, ptr \(addrOf(object))")

        // Determine field index
        let idx: Int
        if let cn = currentClassName, let i = fieldIndex(typeName: cn, fieldName: fieldName) {
            idx = i
        } else {
            var found: Int? = nil
            for (_, decl) in typeDecls {
                if let i = decl.fields.firstIndex(where: { $0.0 == fieldName }) {
                    found = i
                    break
                }
            }
            idx = found ?? 0
        }

        // Load value and convert to i64
        let valType = typeOf(value)
        let valTmp = nextSSA()
        lines.append("\(valTmp) = load \(valType), ptr \(addrOf(value))")

        if valType == "ptr" {
            let castTmp = nextSSA()
            lines.append("\(castTmp) = ptrtoint ptr \(valTmp) to i64")
            lines.append("call void @rockit_object_set_field(ptr \(objTmp), i32 \(idx), i64 \(castTmp))")
        } else if valType == "i1" {
            let extTmp = nextSSA()
            lines.append("\(extTmp) = zext i1 \(valTmp) to i64")
            lines.append("call void @rockit_object_set_field(ptr \(objTmp), i32 \(idx), i64 \(extTmp))")
        } else if valType == "double" {
            let castTmp = nextSSA()
            lines.append("\(castTmp) = bitcast double \(valTmp) to i64")
            lines.append("call void @rockit_object_set_field(ptr \(objTmp), i32 \(idx), i64 \(castTmp))")
        } else {
            lines.append("call void @rockit_object_set_field(ptr \(objTmp), i32 \(idx), i64 \(valTmp))")
        }

        return lines
    }

    // MARK: - Type Mapping

    private func llvmType(_ type: MIRType) -> String {
        switch type {
        case .int, .int64:      return "i64"
        case .int32:            return "i32"
        case .float, .float64, .double: return "double"
        case .bool:             return "i1"
        case .string:           return "ptr"
        case .unit:             return "void"
        case .nothing:          return "void"
        case .nullable:         return "ptr"
        case .reference:        return "ptr"
        case .function:         return "ptr"
        }
    }

    private func llvmArithType(_ type: MIRType) -> String {
        switch type {
        case .float, .float64, .double: return "double"
        case .int32:                    return "i32"
        default:                        return "i64"
        }
    }

    private func isFloatType(_ type: MIRType) -> Bool {
        switch type {
        case .float, .float64, .double: return true
        default: return false
        }
    }

    private func inferCallReturnType(_ function: String) -> String {
        // Check user-defined functions first
        if let retType = functionSignatures[function] {
            let lt = llvmType(retType)
            return lt != "void" ? lt : "void"
        }

        // Builtins
        switch function {
        case "toString", "intToString", "floatToString", "boolToString",
             "stringSubstring", "substring", "charAt", "stringTrim",
             "stringReplace", "stringToLower", "stringToUpper",
             "stringConcat", "stringFromCharCodes", "readLine",
             "fileRead", "getEnv":
            return "ptr"
        case "stringLength", "charCodeAt", "stringIndexOf", "toInt",
             "charToInt", "abs", "min", "max", "listSize", "mapSize":
            return "i64"
        case "listOf", "mutableListOf", "mapOf", "mutableMapOf",
             "listCreate", "mapCreate":
            return "ptr"
        case "startsWith", "endsWith", "stringContains", "isDigit",
             "isLetter", "isWhitespace", "isLetterOrDigit",
             "fileExists", "fileWrite", "fileDelete",
             "isList", "isMap", "listContains", "mapContainsKey",
             "listIsEmpty", "mapIsEmpty":
            return "i1"
        default:
            return "i64"
        }
    }

    // MARK: - Name Helpers

    private func llvmFunctionName(_ name: String) -> String {
        // Replace dots with underscores for method names like "Class.method"
        return name.replacingOccurrences(of: ".", with: "_")
    }

    private func llvmLabel(_ label: String) -> String {
        // Replace dots with underscores in block labels
        return label.replacingOccurrences(of: ".", with: "_")
    }

    private func nextSSA() -> String {
        let name = "%_\(ssaCounter)"
        ssaCounter += 1
        return name
    }

    /// Get the LLVM alloca address for a MIR register name.
    private func addrOf(_ name: String) -> String {
        if let mapped = registerMap[name] {
            return mapped
        }
        // For param references like "param.x"
        if name.hasPrefix("param.") {
            let paramName = String(name.dropFirst(6))
            if let mapped = registerMap["param.\(paramName)"] {
                return mapped
            }
            return "%p.\(paramName)"
        }
        // For temps like "%t0"
        if name.hasPrefix("%t") {
            return "%\(name.dropFirst(1))"
        }
        return "%\(name)"
    }

    /// Get the LLVM type for a MIR register.
    private func typeOf(_ name: String) -> String {
        if let t = registerTypes[name] {
            return t
        }
        if name.hasPrefix("param.") {
            if let t = registerTypes[name] {
                return t
            }
            let paramName = String(name.dropFirst(6))
            if let pt = currentParams.first(where: { $0.0 == paramName }) {
                return llvmType(pt.1)
            }
        }
        return "i64"
    }

    /// Store a value to a temp's alloca.
    private func storeToTemp(_ temp: String, value: String, type: String) -> String {
        return "store \(type) \(value), ptr \(addrOf(temp))"
    }

    // MARK: - String Escaping

    private func llvmEscapeString(_ s: String) -> String {
        var result = ""
        for byte in s.utf8 {
            switch byte {
            case 0x20...0x21, 0x23...0x5B, 0x5D...0x7E:
                // Printable ASCII except " (0x22) and \ (0x5C)
                result.append(Character(UnicodeScalar(byte)))
            default:
                result += String(format: "\\%02X", byte)
            }
        }
        return result
    }
}

// MARK: - Compile to Native

extension LLVMCodeGen {

    /// Compile a .rok source file to a native executable.
    /// Returns the path to the native binary, or throws on error.
    public static func compileToNative(
        source: String,
        fileName: String,
        outputPath: String,
        runtimeDir: String,
        emitLLVM: Bool = false
    ) throws -> String {
        let diagnostics = DiagnosticEngine()

        // Frontend pipeline
        let lexer = Lexer(source: source, fileName: fileName, diagnostics: diagnostics)
        let tokens = lexer.tokenize()
        let parser = Parser(tokens: tokens, diagnostics: diagnostics)
        let ast = parser.parse()
        let checker = TypeChecker(ast: ast, diagnostics: diagnostics)
        let typeResult = checker.check()

        if diagnostics.hasErrors {
            diagnostics.dump()
            throw LLVMCodeGenError.frontendErrors(diagnostics.errorCount)
        }

        // MIR pipeline
        let lowering = MIRLowering(typeCheckResult: typeResult)
        let unoptimized = lowering.lower()
        let optimizer = MIROptimizer()
        let optimized = optimizer.optimize(unoptimized)

        // LLVM IR emission
        let codeGen = LLVMCodeGen()
        let llvmIR = codeGen.emit(module: optimized)

        // Write .ll file
        let llPath = outputPath + ".ll"
        try llvmIR.write(toFile: llPath, atomically: true, encoding: .utf8)

        if emitLLVM {
            return llPath
        }

        // Compile C runtime
        let runtimeObjPath = NSTemporaryDirectory() + "rockit_runtime.o"
        let runtimeSrcPath = runtimeDir + "/rockit_runtime.c"

        let compileRuntime = Process()
        compileRuntime.executableURL = URL(fileURLWithPath: "/usr/bin/clang")
        compileRuntime.arguments = ["-c", "-O1", "-I", runtimeDir, runtimeSrcPath, "-o", runtimeObjPath]
        try compileRuntime.run()
        compileRuntime.waitUntilExit()
        guard compileRuntime.terminationStatus == 0 else {
            throw LLVMCodeGenError.runtimeCompileFailed
        }

        // Compile + link
        let link = Process()
        link.executableURL = URL(fileURLWithPath: "/usr/bin/clang")
        link.arguments = ["-O1", llPath, runtimeObjPath, "-o", outputPath]
        try link.run()
        link.waitUntilExit()
        guard link.terminationStatus == 0 else {
            throw LLVMCodeGenError.linkFailed
        }

        return outputPath
    }
}

// MARK: - Errors

public enum LLVMCodeGenError: Error, CustomStringConvertible {
    case frontendErrors(Int)
    case runtimeCompileFailed
    case linkFailed

    public var description: String {
        switch self {
        case .frontendErrors(let count):
            return "\(count) frontend error(s)"
        case .runtimeCompileFailed:
            return "failed to compile C runtime"
        case .linkFailed:
            return "failed to link native binary"
        }
    }
}
