[package]
name = "rockit-compiler"
version = "0.1.0"

[test]
directory = "tests"

[test.scheme.default]
include = ["*"]
exclude = ["advanced", "core/lib"]

[test.scheme.all]
include = ["*"]
exclude = []
