#!/usr/bin/env bash
# Rockit — Repository Migration Script
# Dark Matter Tech
#
# Extracts the compiler from the moon monorepo into a standalone
# rockit-compiler repository structure.
#
# Usage:
#   ./migrate-to-repo.sh /path/to/output
#
# This script copies files and updates internal path references.
# It does NOT create a git repo — do that manually after inspecting output.

set -euo pipefail

OUTPUT="${1:-}"
if [ -z "$OUTPUT" ]; then
    echo "Usage: migrate-to-repo.sh <output-directory>"
    echo ""
    echo "Creates a standalone rockit-compiler repo structure at <output-directory>."
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\033[1m'
RESET='\033[0m'

info()  { echo -e "${BOLD}==>${RESET} $1"; }
ok()    { echo -e "${GREEN}==>${RESET} $1"; }
fail()  { echo -e "${RED}error:${RESET} $1"; exit 1; }

if [ -d "$OUTPUT" ]; then
    fail "Output directory already exists: $OUTPUT"
fi

info "Migrating rockit-compiler to: $OUTPUT"

# Create directory structure
mkdir -p "$OUTPUT"/{src,runtime,scripts,tests,examples,benchmarks,keys}

# --- Copy source files ---
info "Copying Stage 1 source (self-hosted-rockit/ -> src/)..."
for f in "${PROJECT_DIR}"/self-hosted-rockit/*.rok; do
    [ -f "$f" ] && cp "$f" "$OUTPUT/src/"
done
cp "${PROJECT_DIR}/self-hosted-rockit/build.sh" "$OUTPUT/src/"
chmod +x "$OUTPUT/src/build.sh"

# Copy Stage 1 binary if it exists
if [ -f "${PROJECT_DIR}/self-hosted-rockit/command" ]; then
    cp "${PROJECT_DIR}/self-hosted-rockit/command" "$OUTPUT/src/"
fi

# VERSION goes to root
cp "${PROJECT_DIR}/self-hosted-rockit/VERSION" "$OUTPUT/VERSION"

# --- Copy stdlib as submodule reference ---
info "Creating stdlib submodule reference..."
cat > "$OUTPUT/.gitmodules" << 'GITMODULES'
[submodule "stdlib"]
	path = stdlib
	url = https://rustygits.com/Dark-Matter/launchpad.git
	branch = main
GITMODULES

# Copy stdlib content for now (will be replaced by submodule init)
if [ -d "${PROJECT_DIR}/self-hosted-rockit/stdlib" ]; then
    cp -r "${PROJECT_DIR}/self-hosted-rockit/stdlib" "$OUTPUT/stdlib"
fi

# --- Copy runtime ---
info "Copying runtime..."
cp -r "${PROJECT_DIR}/runtime/"* "$OUTPUT/runtime/"

# --- Copy scripts ---
info "Copying scripts..."
for f in install.sh install.ps1 package.sh sign.sh; do
    if [ -f "${PROJECT_DIR}/scripts/$f" ]; then
        cp "${PROJECT_DIR}/scripts/$f" "$OUTPUT/scripts/"
    fi
done
chmod +x "$OUTPUT"/scripts/*.sh 2>/dev/null || true

# --- Copy tests, examples, benchmarks ---
info "Copying tests, examples, benchmarks..."
if [ -d "${PROJECT_DIR}/tests" ]; then
    cp -r "${PROJECT_DIR}/tests/"* "$OUTPUT/tests/" 2>/dev/null || true
fi
if [ -d "${PROJECT_DIR}/examples" ]; then
    cp -r "${PROJECT_DIR}/examples/"* "$OUTPUT/examples/" 2>/dev/null || true
fi
if [ -d "${PROJECT_DIR}/benchmarks" ]; then
    cp -r "${PROJECT_DIR}/benchmarks/"* "$OUTPUT/benchmarks/" 2>/dev/null || true
fi

# --- Copy keys ---
if [ -d "${PROJECT_DIR}/keys" ]; then
    cp -r "${PROJECT_DIR}/keys/"* "$OUTPUT/keys/" 2>/dev/null || true
fi

# --- Copy docs ---
info "Copying documentation..."
if [ -f "${PROJECT_DIR}/SECURITY.md" ]; then
    cp "${PROJECT_DIR}/SECURITY.md" "$OUTPUT/"
fi

# Create a README for the new repo
cat > "$OUTPUT/README.md" << 'README'
# Rockit Compiler

The Rockit language compiler. Self-hosting — Rockit compiles itself.

> **Status:** All phases complete. Self-hosting bootstrap verified (Stage 2 == Stage 3).

## Install

**macOS / Linux:**
```bash
curl -fsSL https://rustygits.com/Dark-Matter/rockit-compiler/raw/branch/master/scripts/install.sh | bash
```

**Windows (PowerShell):**
```powershell
iwr -useb https://rustygits.com/Dark-Matter/rockit-compiler/raw/branch/master/scripts/install.ps1 | iex
```

## Build from Source

Requires Swift 5.9+ and clang for the initial bootstrap (Stage 0 lives in [Dark-Matter/moon](https://rustygits.com/Dark-Matter/moon)).

```bash
# After Stage 1 binary is available:
src/command build-native src/command.rok
src/command version
```

## Structure

```
src/            Stage 1 compiler source (.rok)
stdlib/         Standard library (submodule: launchpad)
runtime/        C and Rockit runtime
scripts/        Install, package, and signing scripts
tests/          Integration test suites
examples/       Feature test files
benchmarks/     Performance benchmarks
keys/           Public signing keys
```

## License

Proprietary — Dark Matter Tech
README

# --- Create .gitignore ---
cat > "$OUTPUT/.gitignore" << 'GITIGNORE'
# Build artifacts
*.o
*.ll
*.rokb
*.out
*.exe
*.tar.gz

# Concatenated compiler source (generated by build.sh)
src/command.rok

# Editor files
.vscode/
.idea/
*.swp
*~
.DS_Store

# Distribution
dist/
GITIGNORE

# --- Copy CI templates ---
info "Copying CI workflow templates..."
if [ -d "${SCRIPT_DIR}/ci-templates/.github" ]; then
    mkdir -p "$OUTPUT/.github/workflows"
    cp -r "${SCRIPT_DIR}/ci-templates/.github/workflows/"* "$OUTPUT/.github/workflows/"
fi
if [ -d "${SCRIPT_DIR}/ci-templates/.gitea" ]; then
    mkdir -p "$OUTPUT/.gitea/workflows"
    cp -r "${SCRIPT_DIR}/ci-templates/.gitea/workflows/"* "$OUTPUT/.gitea/workflows/"
fi

# --- Update path references ---
info "Updating path references..."

# Fix install.sh
if [ -f "$OUTPUT/scripts/install.sh" ]; then
    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' 's|REPO_COMPILER="Dark-Matter/moon"|REPO_COMPILER="Dark-Matter/rockit-compiler"|g' "$OUTPUT/scripts/install.sh"
        sed -i '' 's|/RockitCompiler/scripts/install.sh|/scripts/install.sh|g' "$OUTPUT/scripts/install.sh"
        sed -i '' 's|Dark-Matter/moon/raw/branch/develop/RockitCompiler/scripts/|Dark-Matter/rockit-compiler/raw/branch/master/scripts/|g' "$OUTPUT/scripts/install.sh"
        sed -i '' 's|/moon/RockitCompiler|/rockit-compiler|g' "$OUTPUT/scripts/install.sh"
        sed -i '' 's|self-hosted-rockit/|src/|g' "$OUTPUT/scripts/install.sh"
        sed -i '' 's|Dark-Matter/moon/raw/branch/develop/scripts/|Dark-Matter/rockit-compiler/raw/branch/master/scripts/|g' "$OUTPUT/scripts/install.sh"
    else
        sed -i 's|REPO_COMPILER="Dark-Matter/moon"|REPO_COMPILER="Dark-Matter/rockit-compiler"|g' "$OUTPUT/scripts/install.sh"
        sed -i 's|/RockitCompiler/scripts/install.sh|/scripts/install.sh|g' "$OUTPUT/scripts/install.sh"
        sed -i 's|Dark-Matter/moon/raw/branch/develop/RockitCompiler/scripts/|Dark-Matter/rockit-compiler/raw/branch/master/scripts/|g' "$OUTPUT/scripts/install.sh"
        sed -i 's|/moon/RockitCompiler|/rockit-compiler|g' "$OUTPUT/scripts/install.sh"
        sed -i 's|self-hosted-rockit/|src/|g' "$OUTPUT/scripts/install.sh"
        sed -i 's|Dark-Matter/moon/raw/branch/develop/scripts/|Dark-Matter/rockit-compiler/raw/branch/master/scripts/|g' "$OUTPUT/scripts/install.sh"
    fi
fi

# Fix install.ps1
if [ -f "$OUTPUT/scripts/install.ps1" ]; then
    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' 's|\$REPO = "Dark-Matter/moon"|\$REPO = "Dark-Matter/rockit-compiler"|g' "$OUTPUT/scripts/install.ps1"
        sed -i '' 's|/RockitCompiler/scripts/install.ps1|/scripts/install.ps1|g' "$OUTPUT/scripts/install.ps1"
        sed -i '' 's|Dark-Matter/moon/raw/branch/develop/RockitCompiler/scripts/|Dark-Matter/rockit-compiler/raw/branch/master/scripts/|g' "$OUTPUT/scripts/install.ps1"
        sed -i '' 's|/moon/RockitCompiler|/rockit-compiler|g' "$OUTPUT/scripts/install.ps1"
        sed -i '' 's|self-hosted-rockit/|src/|g' "$OUTPUT/scripts/install.ps1"
        sed -i '' 's|self-hosted-rockit\\|src\\|g' "$OUTPUT/scripts/install.ps1"
        sed -i '' 's|Dark-Matter/moon/raw/branch/develop/scripts/|Dark-Matter/rockit-compiler/raw/branch/master/scripts/|g' "$OUTPUT/scripts/install.ps1"
    else
        sed -i 's|\$REPO = "Dark-Matter/moon"|\$REPO = "Dark-Matter/rockit-compiler"|g' "$OUTPUT/scripts/install.ps1"
        sed -i 's|/RockitCompiler/scripts/install.ps1|/scripts/install.ps1|g' "$OUTPUT/scripts/install.ps1"
        sed -i 's|Dark-Matter/moon/raw/branch/develop/RockitCompiler/scripts/|Dark-Matter/rockit-compiler/raw/branch/master/scripts/|g' "$OUTPUT/scripts/install.ps1"
        sed -i 's|/moon/RockitCompiler|/rockit-compiler|g' "$OUTPUT/scripts/install.ps1"
        sed -i 's|self-hosted-rockit/|src/|g' "$OUTPUT/scripts/install.ps1"
        sed -i 's|self-hosted-rockit\\|src\\|g' "$OUTPUT/scripts/install.ps1"
        sed -i 's|Dark-Matter/moon/raw/branch/develop/scripts/|Dark-Matter/rockit-compiler/raw/branch/master/scripts/|g' "$OUTPUT/scripts/install.ps1"
    fi
fi

# Fix package.sh
if [ -f "$OUTPUT/scripts/package.sh" ]; then
    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' 's|self-hosted-rockit/|src/|g' "$OUTPUT/scripts/package.sh"
        sed -i '' 's|Dark-Matter/moon|Dark-Matter/rockit-compiler|g' "$OUTPUT/scripts/package.sh"
    else
        sed -i 's|self-hosted-rockit/|src/|g' "$OUTPUT/scripts/package.sh"
        sed -i 's|Dark-Matter/moon|Dark-Matter/rockit-compiler|g' "$OUTPUT/scripts/package.sh"
    fi
fi

# Fix runtime build.sh (references to ../../self-hosted-rockit/command)
if [ -f "$OUTPUT/runtime/rockit/build.sh" ]; then
    if [[ "$(uname)" == "Darwin" ]]; then
        sed -i '' 's|../../self-hosted-rockit/command|../../src/command|g' "$OUTPUT/runtime/rockit/build.sh"
    else
        sed -i 's|../../self-hosted-rockit/command|../../src/command|g' "$OUTPUT/runtime/rockit/build.sh"
    fi
fi

# --- Summary ---
echo ""
ok "Migration complete!"
echo ""
echo "  Output: $OUTPUT"
echo ""
echo "  Directory structure:"
find "$OUTPUT" -maxdepth 2 -type d | sort | while read -r d; do
    echo "    ${d#$OUTPUT/}"
done
echo ""
echo "  Next steps:"
echo "    cd $OUTPUT"
echo "    git init"
echo "    git submodule add https://rustygits.com/Dark-Matter/launchpad.git stdlib"
echo "    git add -A"
echo "    git commit -m 'Initial import from moon monorepo'"
echo "    git remote add origin https://rustygits.com/Dark-Matter/rockit-compiler.git"
echo "    git push -u origin master"
echo ""
