#!/bin/bash
# Build the Stage 1 compiler by concatenating modules.
# Each module is a .moon file. The last module provides the main() function.
# Usage: ./build.sh [module1.moon module2.moon ...] output.moon

STAGE1_DIR="$(cd "$(dirname "$0")" && pwd)"

# Strip the main() function from a file (everything from the last "fun main" to EOF)
strip_main() {
    awk '/^fun main\(\)/ { found=1 } !found { print }' "$1"
}

# Default: build lexer + parser into a combined file
OUTPUT="${STAGE1_DIR}/moonc.moon"

echo "// moonc.moon — Stage 1 Moon Compiler (auto-generated)" > "$OUTPUT"
echo "// Generated by build.sh — do not edit directly" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Lexer (without main)
strip_main "${STAGE1_DIR}/lexer.moon" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Parser (with main)
cat "${STAGE1_DIR}/parser.moon" >> "$OUTPUT"

echo "Built: $OUTPUT"
