#!/bin/bash
# Build the Stage 1 compiler by concatenating modules.
# Each module is a .rok file. The last module provides the main() function.
# Usage: ./build.sh [module1.rok module2.rok ...] output.rok

STAGE1_DIR="$(cd "$(dirname "$0")" && pwd)"

# Strip the main() function from a file (everything from the last "fun main" to EOF)
strip_main() {
    awk '/^fun main\(\)/ { found=1 } !found { print }' "$1"
}

# Default: build lexer + parser + typechecker + optimizer + codegen into a combined file
OUTPUT="${STAGE1_DIR}/command.rok"

echo "// command.rok — Stage 1 Rockit Compiler (auto-generated)" > "$OUTPUT"
echo "// Generated by build.sh — do not edit directly" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Lexer (without main)
strip_main "${STAGE1_DIR}/lexer.rok" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Parser (without main)
strip_main "${STAGE1_DIR}/parser.rok" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Type checker (without main)
strip_main "${STAGE1_DIR}/typechecker.rok" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Optimizer (without main)
strip_main "${STAGE1_DIR}/optimizer.rok" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# LLVM IR generator (without main)
strip_main "${STAGE1_DIR}/llvmgen.rok" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Code generator (with main)
cat "${STAGE1_DIR}/codegen.rok" >> "$OUTPUT"

echo "Built: $OUTPUT"
